defaultBranch: 'main'
branchName: '${issue.number}'
branches:
  - label: '*'
    prefix: issues/
  - label: 🚀 feature
    prefix: feature/
  - label: 🛠 refactor
    prefix: refactor/
  - label: 🐞 bug
    prefix: bugfix/
autoCloseIssue: true